#!/bin/sh

# TODO
record_dir="$XDG_VIDEOS_DIR/Herbert"

updatestatus() { \
	echo "$1" > /tmp/recordingicon
}

killrecording() {
	recpid="$(cat /tmp/recordingpid)"
	# kill with SIGTERM, allowing finishing touches.
	kill -15 "$recpid"
	rm -f /tmp/recordingpid
	updatestatus ""
	# even after SIGTERM, ffmpeg may still run, so SIGKILL it.
  notify-send " Recording" "Screencast stopped."
	sleep 3
	kill -9 "$recpid" &>/dev/null
	exit
}

screencast() { \
    filename="$record_dir/[$(date '+%y%m%d-%H%M-%S')] screencast" 
    ffmpeg -y \
	-f x11grab \
	-framerate 60 \
	-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
	-i $DISPLAY \
	-f alsa -i default \
	-r 30 \
 	-c:v libx264rgb -crf 0 -preset ultrafast -c:a flac \
	"$filename.mkv" & \
	echo $! > /tmp/recordingpid 
	updatestatus "screencast" 
  notify-send "⏺ Recording" "Screencast started."
}

video() { \
    filename="$record_dir/[$(date '+%y%m%d-%H%M-%S')] video" 
	ffmpeg \
	-f x11grab \
	-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
	-i $DISPLAY \
 	-c:v libx264 -qp 0 -r 30 \
	"$filename.mkv" &
	echo $! > /tmp/recordingpid
	updatestatus "video"
  notify-send "⏺ Recording" "Screencast started."
}

audio() { \
    filename="$record_dir/[$(date '+%y%m%d-%H%M-%S')] audio" 
	ffmpeg \
	-f alsa -i default \
	-c:a flac \
	"$filename.flac" &
	echo $! > /tmp/recordingpid
	updatestatus "🎙️"
  notify-send "⏺ Recording" "Audio started."
}

askrecording() { \
	choice=$(printf "screencast\\nvideo\\naudio" | rofi -dmenu -i -p "recording:")
	case "$choice" in
		screencast) screencast;;
		audio) audio;;
		video) video;;
	esac
}

asktoend() { \
	response=$(printf "No\\nYes" | rofi -dmenu -i -p "recording still active, end recording:") &&
	[ "$response" = "Yes" ] &&  killrecording 
}


case "$1" in
	screencast) screencast;;
	audio) audio;;
	video) video;;
	kill) killrecording;;
	*) ([ -f /tmp/recordingpid ] && asktoend && exit) || askrecording;;
esac

