#!/bin/sh

#〖愛〗emoji-rofi - select emoji and copy to clipboard

# Housekeep
err() { 
	printf "Error: xsel command not found. Please install xsel.\n" 
}
xsel --version &>/dev/null || err && exit 1

# Get emojis
chosen=`cut -d ';' -f1 ~/.local/share/emoji_rofi/emoji | \
	rofi -dmenu -i -p emoji | \
	sed "s/ .*//"
`
[ "$chosen" == "" ] && exit

echo "$chosen" | tr -d '\n' | xsel --clipboard
notify-send "emoji" "'$chosen' copied to clipboard."
