#!/bin/sh

#〖愛〗rofi_pass - select a password from a rofi menu and copy it to the clipboard for a few seconds

# Usage:
#   pass_rofi

# select password
password=$(
	rg --files "$PASSWORD_STORE_DIR" | \
	sed 's,'"$PASSWORD_STORE_DIR/"',,g; s/.gpg//g' | \
	rofi -dmenu -p "pass"
)

# copy password to clipboard
if [ ! -z $password ]; then
	p=$(pass $password)
	echo "$p" | xsel --clipboard &>/dev/null &&
	notify-send " pass" "'$password' password copied to clipboard."
fi

# clear clipboard
sleep 4 && echo "" | xsel --clipboard
