#! /bin/sh

# This script executes the entrtasks script in a tmux session. 
# I'm too incompetent to get it to start normally in ~/.xprofile.

tmux kill-session -t entrtasks
tmux new -s entrtasks -d
tmux send -t entrtasks entrtasks ENTER

notify-send "Entrtasks (script)" "Successfully started watching files."
