#!/bin/sh

#〖愛〗statusbar_music - print song details and music volume

# REQUIRED: mpc 

stat=`mpc status -f '%title%'`

# Mpd is not running or playlist empty

case "$stat" in
	*n/a*) exit ;;
esac
[ -z "$stat" ] && exit

# Get volume
vol=`echo "$stat" | grep 'volume'`
vol="${vol#volume:}"
vol="${vol%%\%*}"

# Get playing/paused icon
icon=`echo "$stat" | sed -n '2p'`
icon=${icon#\[}
icon=${icon%\]*}
case $icon in
	playing) icon='';;
	paused) icon=''
esac

# Truncate song name if n chars or longer
song="`echo "$stat" | sed -n '1p'`"
n=21
[ ${#song} -ge $n ] && 
song="`echo $song | colrm $(( $n - 2 ))`..."

printf "〚 $vol $icon $song 〛"
