#!/bin/sh

# Show wifi  and percent strength or  if none.
# Show  if connected to ethernet or '' if none.

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifiicon=" ";;
	up) wifiicon="$(
		awk '/^\s*w/ { print "", int($3 * 100 / 70) "% " }' \
			/proc/net/wireless
		)";;
esac

printf "〚 %s%s 〛" \
	"$(echo $wifiicon | sed 's/\%//')" \
	"$(sed "s/down//;s/up/ /" /sys/class/net/e*/operstate 2>/dev/null)"
