#!/bin/sh

#〖愛〗statusbar_memavail - print available memory

# This script prints the current free memory (in GiB) to 
# stdout.

available=$( awk \
	'/MemAvailable/ { printf "%.2f", $2/1024/1024 }' \
	/proc/meminfo
)

printf "〚 $available "
