#!/bin/sh

#〖愛〗statusbar_volume - print the system volume level

sink=`pactl list short sinks | grep 'RUNNING' | awk '{print $1}'`

volstat=`pactl list sinks`
# Split string up until active sink
volstat=`echo ${volstat##*Sink #$sink}`
# Sink is muted
echo "$volstat" | grep -q "Mute: yes" &&
	printf "〚  〛" && exit

# Split string to get volume level
volstat=`echo ${volstat##*Volume: front-}`
volstat=`echo ${volstat#*\/}`
vol=`echo ${volstat%%\%*}`

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -gt "30" ]; then
	icon=""
else
	icon=""
fi

printf "〚 $vol $icon 〛"
