#!/bin/sh

#〖愛〗emoji-rofi - select emoji and copy to clipboard

xsel --version 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 ~/.local/share/emoji_rofi/emoji | rofi -dmenu -i -p emoji | sed "s/ .*//")

[ "$chosen" != "" ] || exit

# If you run this command with an argument, it will automatically insert the character.
if [ -n "$1" ]; then
	xdotool key Shift+Insert
else
	echo "$chosen" | tr -d '\n' | xsel --clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
