#!/bin/sh

# This script is a rofi version of `passmenu`. It allows the user to
# select a password to copy to the clipboard through a rofi -dmenu.
#
# Usage:
#   pass_rofi

passdir=".password-store"

# select password
password=$(
    rg --files $HOME/$passdir | \
    sed "s/\/home\/$(whoami)\/$passdir\///g; s/.gpg//g" | \
    rofi -dmenu -p "pass"
)

# copy password to clipboard
if [ ! -z $password ]; then
    pass $password | xsel --clipboard &>/dev/null && \
    notify-send "Pass" "'$password' password copied to clipboard."
fi
