#!/bin/sh

#〖愛〗rofi_mount - unmount usb devices

# REQUIRED: rofi

# Get all unmountable drives, quit if none found
drives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')
[ -z "$drives" ] && notify-send " USB unmounting" "no drives to unmount." && exit

# Pick device to unmount, quit if none found
chosen=$(echo "$drives" | rofi -dmenu -p "Choose device to unmount" | awk '{print $1}')
[ -z "$chosen" ] && exit

# Unmount device
sudo -A umount "$chosen" && \
pkill -RTMIN+18 dwmblocks && \
notify-send " USB unmounting" "<u><b>$chosen</b></u> unmounted."
