#!/bin/sh

#〖愛〗dmenu_pass - select a password from a menu and copy it to the clipboard for a few seconds

# Usage:
#   dmenupass

# select password
password=$(
	rg --files "$PASSWORD_STORE_DIR" | \
	sed 's,'"$PASSWORD_STORE_DIR/"',,g; s/.gpg//g' | \
	dmenu 
)

# copy password to clipboard
if [ ! -z "$password" ]; then
	p=$(pass $password) &&
	echo "$p" | xclip -sel clip &&
	notify-send " pass" "'$password' password copied to clipboard."
fi

# clear clipboard
sleep 4 && echo "" | xclip -sel clip
