#!/bin/sh

#〖愛〗rofi_mount - mount usb devices

# REQUIRED: rofi

# Get mountable devices, quit if none found
devices="$(
	lsblk -rpo "name,type,size,mountpoint" |
	awk '!/sdb[1-6]/ && $2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}'
)"
[ -z "$devices" ] && exit

# Pick device, quit if none selected
device=$(
	echo "$devices" |
	rofi -dmenu -p "Choose device to mount:" |
	awk '{print $1}'
)
[ -z "$device" ] && exit

# Find all mountable dirs in /mnt, quit if none available
dirs="$(
	find /mnt -maxdepth 1 ! -path /mnt -type d | sed "s/\/mnt\///"
)"
mounted=`mount | awk '/mnt/{print $3}'`
while IFS= read -r d; do
	while IFS= read -r m; do
		[ "$m" = "/mnt/$d" ] && \
		dirs=`echo "$dirs" | sed "/$d/d"`
	done <<< "$mounted"
done <<< "$dirs"
[ -z "$dirs" ] && exit

# Pick dir to mount to, quit if none selected
dir=$(
	echo $dirs |
	rofi -sep ' ' -dmenu -p "Choose location to mount to:"
)
[ -z "$dir" ] && exit

# Mount and notify
mp="/mnt/$dir"
mkdir -p "$mp"
sudo -A mount -o uid=1000,gid=985,fmask=117,dmask=007 \
	"$device" "$mp" && \
pkill -RTMIN+18 dwmblocks && \
notify-send " USB mount" \
	"successfully mounted <u><b>'$device'</b></u> to <u><b>'$dir'</b></u>"
