#!/bin/sh

#〖愛〗vpwd_cf - quickly access files

# Usage:
#   source vpwd_cf

f="`cf_fzf`"

# Edit file
editor="$EDITOR"
command -v vpwd_nvim &>/dev/null && EDITOR="vpwd_nvim"
[ -z "$f" ] || $EDITOR "$f"
EDITOR="$editor"
unset editor
[ -f /tmp/vpwd/term-${TERM_ID} ] &&
vpwd_dir=`</tmp/vpwd/term-${TERM_ID}` &&
cd "$vpwd_dir" || true
