#!/bin/sh

#〖愛〗start_compton - restart compton

killall -q compton
compton --config /home/sarrost/.config/compton/compton.conf & disown
notify-send "✓ Compton" "Window compositor successfully launched."
