#!/bin/sh

#〖愛〗statusbar_batstatus - print battery status as icon

s="`cat /sys/class/power_supply/BAT1/status`"

case "$s" in
	Unknown) icon="∞";;
	Charging) icon="";;
	Discharging) icon="";;
	*) icon="";;
esac

printf "〚 $icon "
