#!/bin/sh

#〖愛〗statusbar_volume - print the system volume level

volstat="`pactl list sinks`"
echo "$volstat" | grep -q "Mute: yes" && \
	printf "〚  〛" && exit

vol="$(echo "$volstat" | grep '[0-9]\+%' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -gt "30" ]; then
	icon=""
else
	icon=""
fi

printf "〚 $vol $icon 〛"
