#!/bin/sh

#〖愛〗statusbar_batcapacity - print the current battery capacity 

capacity="`cat /sys/class/power_supply/BAT1/capacity`"

symbol=""
if [ "$capacity" -lt 85 ]; then
	symbol=""
elif [ "$capacity" -lt 50 ]; then
	symbol=""
elif [ "$capacity" -lt 25 ]; then
	symbol=""
elif [ "$capacity" -lt 10 ]; then
	symbol=""
fi

printf "$capacity $symbol 〛"
