#!/bin/sh

#〖愛〗cf - quickly access files

# Usage:
#   cf

# Runs `fzf` on $XDG_CONFIG_HOME/cf and opens the selected 
# file in the text editor. Be sure to set the respective 
# environment variables before running this script.

cf_dir="${XDG_CONFIG_HOME}cf"

# This script's filename (for use in output)
script_name=`basename -- "$0"`
script_name=${0##*\/}

# Some colors
COLOR1='\033[0;31m' # Standard RED
NC='\033[0m' # No Color

# Housekeep
cf_err() {
	>&2 echo -e \
	"${COLOR1}${script_name}${NC}: ${COLOR1}error${NC}:"\
	"'${COLOR1}\$XDG_CONFIG_HOME/cf${NC}'"\
	"does not exist."
}
editor_err() {
	>&2 echo -e \
	"${COLOR1}${script_name}${NC}: ${COLOR1}error${NC}:"\
	"Please set the '${COLOR1}\$EDITOR${NC}'"\
	"environment variable."
}
[ -z "$cf_dir" ] && cf_err && exit 1
[ -z "$EDITOR" ] && editor_err && exit 1

# The job
rg --files --hidden --follow "${XDG_CONFIG_HOME}cf" \
	| fzf | xargs -r $EDITOR
