#!/bin/sh

#〖愛〗cf - quickly access files with fzf

# Runs `fzf` on this dir
cf_dir="${XDG_CONFIG_HOME:-$HOME/.config}cf"
# Be sure to create the dir and populate it with symbolic 
# links to the files/dirs you want quick access to.

# Housekeep
err_cf() {
	printf "Error: '\$XDG_CONFIG_HOME/cf' does not exist.\n"
	exit 1
}
[ -z "$cf_dir" ] && err_cf

# The job
escaped_cf_dir=$(echo $cf_dir | sed 's/\//\\\//g')
f=`rg --files --hidden --follow "${XDG_CONFIG_HOME}cf" | \
	sed "s/$escaped_cf_dir\///" | fzf`
[ -z "$f" ] || printf "$cf_dir/$f"
