#!/bin/sh

#〖愛〗devour - open files with default programs

# Usage:
#   devour FILE

videos=()

for f in "$@"; do
	case "$f" in
		# Video
		*.3gp|*.avi|*.m4v|*.mkv|*.mov|*.mp4|*.mpeg|*.mpg|*.mts|*.ts|*.webm|*.wmv) 
				videos+=("$f")
				;;
		# Audio
		*.mp3|*.wav|*.flac|*.m4a|*.ogg|*.opus) 
				/bin/sh -c "st -e mpv '$f'" &>/dev/null & disown
				;;
		# Misc
		*.pdf|*.djvu) 
				zathura "$f" &>/dev/null & disown
				;;
		*) $EDITOR "$f"
	esac
done

# if [ ! -z "$videos" ]; then
# 	for f in ${videos[@]}; do
# 		echo $f
# 		# mpv "$*" &>/dev/null & disown;;
# 	done
# fi
