#!/bin/sh

#〖愛〗devour - open files with default programs

# Usage:
#   devour FILE

for f in "$@"; do
	case "$f" in
		# Video
		*.3gp|*.avi|*.m4v|*.mkv|*.mov|*.mp4|*.mpeg|*.mpg|*.mts|*.ts|*.webm|*.wmv) 
				videos+=("$f");;
		# Audio
		*.mp3|*.wav|*.flac|*.m4a|*.ogg|*.opus) 
				music+=("$f");;
		# Misc
		*.pdf|*.djvu) 
				docs+=("$f");;
		*.sc)
				sheets+=("$f");;
		*.o)
				objects+=("$f");;
		*) $EDITOR "$f"
	esac
done

[ -z "$videos" ] || mpv "${videos[@]}"
[ -z "$music" ] || mpv "${music[@]}"
[ -z "$docs" ] || zathura "${docs[@]}"
[ -z "$sheets" ] || sc-im "${sheets[@]}"
[ -z "$objects" ] || nm "${objects[@]}" | $EDITOR -R
