#!/bin/sh

#〖愛〗ext - extract files from archives

# Usage:
#   ext [-c]

# - c
#   Extract contents into current directory.

# script name
s=${0##*/}

# Process args
while getopts "hc" o; do case "${o}" in
	c) extracthere="True" ;;
	*) printf "Options:\\n    -c: Extract archive into current directory rather than a new one.\\n" && exit ;;
esac done

if [ -z "$extracthere" ]; then
	archive="$(readlink -f "$*")" &&
	directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
	mkdir -p "$directory" &&
	cd "$directory" || exit
else
	archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)")"
fi

[ "$archive" = "" ] && printf "$s: Give archive to extract as argument.\\n" && exit 1

if [ -f "$archive" ] ; then
	case "$archive" in
		*.tar.bz2|*.tbz2) tar xvjf "$archive" ;;
		*.tar.xz) tar -xf "$archive" ;;
		*.tar.gz|*.tgz) tar xvzf "$archive" ;;
		*.lzma) unlzma "$archive" ;;
		*.bz2) bunzip2 "$archive" ;;
		*.rar) unrar x -ad "$archive" ;;
		*.gz) gunzip "$archive" ;;
		*.tar) tar xvf "$archive" ;;
		*.zip) unzip "$archive" ;;
		*.Z) uncompress "$archive" ;;
		*.7z) 7z x "$archive" ;;
		*.xz) unxz "$archive" ;;
		*.exe) cabextract "$archive" ;;
		*) printf "$s: '%s' - unknown archive method\\n" "$archive" ;;
	esac
else
	printf "$s: File \"$archive\" not found.\\n"
fi
