#!/bin/sh

#〖愛〗pwdclipboard - copy the working dir to the clipboard

# Usage:
#   pwdclipboard [FILE]

# - FILE
#   if provided $PWD/FILE will be copied to clipboard 
#   instead.

# REQUIRED: xclip 

# Script name
name=${0##*\/}

# The job
p="$(pwd)" &>/dev/null
if [ ! -z "$1" ]; then # an arg is passed
	# arg is an existing file/dir
	if [ -a "$p/$1" ] || [ -d "$p/$1" ]; then
		p="$p/$1"
		notify-send "📋 $name" \
			"'<u><b>$p</b></u>' copied to clipboard."
	else # arg is invalid file/dir, just copy $PWD
		a="'<u><b>$1</b></u>' was not found. "
		b="Only '<u><b>$p</b></u>' was copied to clipboard."
		notify-send "❌ $name" "$a$b"
		exit 1
	fi
else # no arg passed, just copy $PWD.
	notify-send "📋 $name" \
		"'<u><b>$p</b></u>' copied to clipboard."
fi

echo "$p" | xclip -sel clip
