#!/bin/sh

#〖愛〗remapkeys - ramap certain keys

# REQUIRED: xcape

# Remaps:
#   L_CTRL <- SUPER
#   CAPS <- ESC and CTRL
#   ESC <- CAPS

# Repeat keys faster when held down
xset r rate 300 50

# Without a delay keys don't remap for some reason.
sleep 2

# Remove Caps_Lock modifier from real Caps Lock key
xmodmap -e "clear Lock"
# Do the same with Ctrl keys
xmodmap -e "clear Control"

# Set real Caps Lock key to present as (right) control
xmodmap -e "keycode 66 = Control_R"
# Set real Escape key to present as Caps Lock
xmodmap -e "keycode 9 = Caps_Lock"
# Make a fake key to hold the Escape keysym, so xcape can 
# use it
xmodmap -e "keycode 255 = Escape"

# Remove Hyper_L from Mod4 group
xmodmap -e "remove Mod4 = Hyper_L"
# Add (left) control to Mod4 group
xmodmap -e "add Mod4 = Control_L"
# Add (right) control to Control group
xmodmap -e "add Control = Control_R"

# Make Caps_Lock work as one would expect
xmodmap -e "add Lock = Caps_Lock"
# Use xcape to map Escape to Caps key.
xcape -e '#66=Escape'
