#!/bin/sh

#〖愛〗screenkeytoggle - toggle screenkey

# Usage:
#   screenkeytoggle [SCREEN]

# - SCREEN
#   Specify a screen for the screenkey to appear on.
#   If no arg is given then display 0 is used instead.

# REQUIRED: screenkey

screen="$1"
[ ! -z "$screen" ] || screen=0

if ( killall screenkey ) &>/dev/null; then
    notify-send "screenkey" "⌨ off"
else
    screenkey \
			--no-systray \
			-t 1 \
			--font-color "#09e8a5" \
			--font "Hack" \
			--scr "$screen" \
			&>/dev/null & disown && \
    notify-send "screenkey" "⌨ on" 
fi
