#!/bin/sh

#〖愛〗screenshot - take screenshots

# Usage:
#   screenshot [args]

#	-	args
#		See scrot(1).

$( scrot '%Y%m%d-%H%M%S-$wx$h.png' \
	-e "mv \$f ${RICE_SCREENSHOT_DIR:-${XDG_PICTURES_DIR:-$HOME}}" \
	--quality 100 \
	--silent \
	$* && \
	notify-send "📸 scrot" "screenshot saved"
) & disown
