#!/bin/sh

#〖愛〗setwallpaper - set the desktop background

# Usage:
#   setwallpaper [--verbose] [FILE]

# Sets the wallpaper to FILE and replaces the default image
# found in the config folder. If no argument is given then
# the default image is used. If no FILE is specified and no
# default image is found the program exits with status
# code 1.

# REQUIRED: xwallpaper

# TODO quiet arg flag
verbose=false

# Wallpaper dir and filename
walldir="$XDG_CONFIG_HOME/setwallpaper"
wallname="wall"
wallfull="$walldir/$wallname"

# This script's filename (for use in output)
script_name=`basename -- "$0"`

# Some colors.
COLOR1='\033[0;31m' # Standard RED
NC='\033[0m' # No Color

# Create walldir if it doesn't exist
[ ! -d $walldir ] && \
mkdir -p $walldir && \
[ $verbose = true ] && echo -e "\n$script_name:"\
	"Wallpaper directory not found, creating"\
	"'$COLOR1$walldir/$NC'."

# wall file exists and an arg is passed, set that as wall
if ( ls $wallfull.* ) &>/dev/null && [ ! -z "$1" ]; then
	filename=$(basename -- "$1")
	ext=${filename##*.}
	existingfile=$(ls $wallfull.* | head -1)
	rm -f $wallfull.*
	cp "$1" $wallfull.$ext
	[ $verbose = true ] && echo -e "\n$script_name:"\
		"File found in config dir, replacing"\
		"'$COLOR1$( basename -- $existingfile )$NC' with"\
		"'$COLOR1$1$NC'."
# wall file exists and no arg is passed, just use wall
elif ( ls $wallfull.* ) &>/dev/null; then
	file="$(ls $wallfull.*)"
	filename=$(basename -- "$file")
	ext="${filename##*.}"
	[ $verbose = true ] && echo -e "\n$script_name:"\
		"No file given as arg, using default"\
		"'$COLOR1$wallname.$ext$NC'."
# wall file does not exist and arg is passed, replace wall
elif [ ! -z "$1" ]; then
	filename=$(basename -- "$1")
	ext=${filename##*.}
	cp "$1" $wallfull.$ext
	[ $verbose = true ] && echo -e "\n$script_name:"\
		"No file found in config dir, creating"\
		"'$COLOR1$wallname.$ext$NC' from '$COLOR1$1$NC'."
# there is no wall file and no arg is passed, exit with
# status 1
else
	error="$script_name: Error: "
	error="${error}No file found in cofig dir and no "
	error="${error}argument given."
	suggestion="$script_name: "
	suggestion="${suggestion}Run '$COLOR1$script_name "
	suggestion="${suggestion}file$NC' to set \`file\` as "
	suggestion="${suggestion}wallpaper."
	>&2 echo -e "\n"$error"\n"$suggestion"\n"
	exit 1
fi

# set the wallpaper
xwallpaper --zoom $wallfull.$ext && \
[ $verbose = true ] && echo -e "\n$script_name:"\
	"${COLOR1}Wallpaper updated.$NC\n"
notify-send " setwallpaper" "Wallpaper updated."
