#!/bin/sh

#〖愛〗statusbar_mounted - <~~>

# Usage:
#   statusbar_mounted

# - <~~>
#   <~~>

devices=`lsblk -nrpo "name,type,size,mountpoint" | 
awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}'`
[ -z "$devices" ] && exit

devices=`echo "$devices" | sed "s/\/mnt\///" | tr '\n' '|' | sed 's/|/  /g'`

printf "〚 $devices 〛"
