#!/bin/sh

#〖愛〗up - quickly update system packages

eix-sync
emerge --update --deep --newuse -q @world
# TODO manually installed programs
# TODO vim plugins
# TODO coc plugins
# TODO --no-sync option
# TODO auto update portage if need be
