#! /bin/sh

# This script prints the tag status of herbstclient in
# a fancy format.

empty=・
nonempty=何
active=愛
otheractive=
otherotheractive=♦
other=⬢
scratchempty=_
scratchactive=
scratchnonempty=

herbstclient tag_status $1 | sed \
's/\t/ /g; s/^ //; s/\.[0-9]\+\b/'"$empty"'/g;
s/\#[0-9]\+\b/'"$active"'/g;
s/\:[0-9]\+\b/'"$nonempty"'/g;
s/\-[0-9]\+\b/'"$otheractive"'/g;
s/\%[0-9]\+\b/'"$otherotheractive"'/g;
s/\+[0-9]\+\b/'"$other"'/g;
s/\.[[:alpha:]_]\{1,\}//g;
s/\#[[:alpha:]_]\{1,\}//g;
s/\:[[:alpha:]_]\{1,\}//g;
s/\-[[:alpha:]_]\{1,\}//g;
s/\%[[:alpha:]_]\{1,\}//g;
s/\+[[:alpha:]_]\{1,\}//g;'
